services:
  stremio-intelldebridsearch:
    container_name: stremio-intelldebridsearch
    image: nepiraw/stremio-intelldebridsearch:latest
    restart: unless-stopped
    ports:
      - 3001:3001
    env_file:
      - .env